package com.example.java;

import com.example.java.OutputUtils;
import org.jfugue.player.Player;
public class Out {
	public static void main(String[] args) {
		OutputUtils outputUtils = new OutputUtils();
		String note1 = new String();
		String note2 = new String();
		String note3 = new String();
		String note4 = new String();
		String note5 = new String();
		String note6 = new String();
		String note7 = new String();
		String note8 = new String();
		String note9 = new String();
		String note10 = new String();
		String note11 = new String();
		String note12 = new String();
		String note13 = new String();
		String note14 = new String();
		String note15 = new String();
		String note16 = new String();
		String note17 = new String();
		String note18 = new String();
		String note19 = new String();
		String note20 = new String();
		String note21 = new String();
		String note22 = new String();
		String note23 = new String();
		String note24 = new String();
		String note25 = new String();
		String track1 = outputUtils.defineTrack();
		String song1 = outputUtils.defineSong();
		note1 = outputUtils.modifyNote("C");
		note2 = outputUtils.modifyNote("C");
		note3 = outputUtils.modifyNote("D");
		note4 = outputUtils.modifyNote("C");
		note5 = outputUtils.modifyNote("F");
		note6 = outputUtils.modifyNote("E");
		note7 = outputUtils.modifyNote("C");
		note8 = outputUtils.modifyNote("C");
		note9 = outputUtils.modifyNote("D");
		note10 = outputUtils.modifyNote("C");
		note11 = outputUtils.modifyNote("G");
		note12 = outputUtils.modifyNote("F");
		note13 = outputUtils.modifyNote("C");
		note14 = outputUtils.modifyNote("C");
		note15 = outputUtils.modifyNote("B");
		note16 = outputUtils.modifyNote("G");
		note17 = outputUtils.modifyNote("E");
		note18 = outputUtils.modifyNote("D");
		note19 = outputUtils.modifyNote("A");
		note21 = outputUtils.modifyNote("A");
		note22 = outputUtils.modifyNote("F");
		note23 = outputUtils.modifyNote("G");
		note24 = outputUtils.modifyNote("F");
		note25 = outputUtils.modifyNote("R");
		track1 = outputUtils.trackAddNote(track1, note1);
		track1 = outputUtils.trackAddNote(track1, note2);
		track1 = outputUtils.trackAddNote(track1, note3);
		track1 = outputUtils.trackAddNote(track1, note4);
		track1 = outputUtils.trackAddNote(track1, note5);
		track1 = outputUtils.trackAddNote(track1, note6);
		track1 = outputUtils.trackAddNote(track1, note25);
		track1 = outputUtils.trackAddNote(track1, note7);
		track1 = outputUtils.trackAddNote(track1, note8);
		track1 = outputUtils.trackAddNote(track1, note9);
		track1 = outputUtils.trackAddNote(track1, note10);
		track1 = outputUtils.trackAddNote(track1, note11);
		track1 = outputUtils.trackAddNote(track1, note12);
		track1 = outputUtils.trackAddNote(track1, note25);
		track1 = outputUtils.trackAddNote(track1, note13);
		track1 = outputUtils.trackAddNote(track1, note14);
		track1 = outputUtils.trackAddNote(track1, note15);
		track1 = outputUtils.trackAddNote(track1, note16);
		track1 = outputUtils.trackAddNote(track1, note17);
		track1 = outputUtils.trackAddNote(track1, note18);
		track1 = outputUtils.trackAddNote(track1, note19);
		track1 = outputUtils.trackAddNote(track1, note21);
		track1 = outputUtils.trackAddNote(track1, note22);
		track1 = outputUtils.trackAddNote(track1, note23);
		track1 = outputUtils.trackAddNote(track1, note24);
		track1 = outputUtils.changeTempo(track1, 0.4);
		song1 = outputUtils.songAddTrack(song1, track1);
		song1 = outputUtils.setSongDuration(song1, 3);
		Player player = new Player();
		player.play(song1);
	}
}
